rails_demo/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'say/hello'
  get 'say/goodbye'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

rails_demo/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @tiempo = Time.now
  end

  def goodbye
  end
end

rails_demo/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @name = 'Danny'
  end
end

rails_demo/app/helpers/say_helper.rb
module SayHelper
end

rails_demo/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rails_demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

rails_demo/app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>

<p>esto es goodbye</p>

rails_demo/app/views/say/hello.html.erb
<h1> Hello from Rails!</h1>

<p>It is now <%= Time.now %></p>

<p>It is now  desde controller <%= @tiempo %></p>
<p><a href="/say/goodbye/">GoodBye</a>!</p>

<p> con route <%= link_to 'Goodbye', say_goodbye_path %></p>

rails_demo/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>
<p>Mi nombre es: <%= @name %> </p>